name: doc_pdf_net
description: Doc PDF net
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
